### ISSUE TITLE
Add Cobalt & Futurium template

### ISSUE THREAD

**Issue by IkiaeM** [GIGABAIT-Official/TemplateSwitch#2]
Add Cobalt & Futurium template

**Comment by aidanarredondo** [comment]
Whom ever the template author is would have to add support to this module, this module is also out of date. 

> Add Cobalt(Drew/ColdFire) & Futurium template

**Comment by PadowYT2** [comment]
As I don't have a lot of template bought, template owner will have to add support to it, but ill add it in the module
